### ISSUE TITLE
What uberduck really needs is the voice of Bruce Willis

### ISSUE THREAD

**Issue by go-dockly** [uberduck-ai/uberduck-ml-dev#132]
This is a personal issue close to my heart.
When I was a child growing up we had the voice of Bruce the fuck Willis in our car navi and it would talk exactly like die hard.
Unfortunately, never found that again.
Not sure how you add voices but Bruce Willis is surely a must have.

**Comment by YTR76** [comment]
do that in the channel #voice-suggestions on the discord server
