### ISSUE TITLE
how to train my voice for tts then voice to voice ?

### ISSUE THREAD

**Issue by Pimax1** [uberduck-ai/uberduck-ml-dev#145]
Hi guys, its a bit hard for me to figure out what are the steps to follow to achieve something great. 

I would like to train a voice first for tts and then for voice to voice in order to match other singers samples.

how to process ? what do you use for the voice to voice RADTTS ? 

thank you very much

**Comment by sjkoelle** [comment]
Hi.  Right now our production voice-to-voice inference code is in this branch

https://github.com/uberduck-ai/uberduck-ml-dev/pull/142

which we will merge soon.

Unfortunately, we don't have training code in there at the moment - you're best bet is to take it from here https://colab.research.google.com/github/justinjohn0306/so-vits-svc/blob/4.0/Sovits4_training_inference.ipynb#scrollTo=pCqf3W0d6ify

Radtts is for text-to-speech not voice-to-voice right now.  We are working on a radtts fine tuning notebook, but it may be easier to use https://colab.research.google.com/drive/1jF-Otw2_ssEcus4ISaIZu3QDmtifUvyY

Does that help?

**Comment by Pimax1** [comment]
thank you so much, i will check :)
