### ISSUE TITLE
Regarding Character Voice Cloning

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [uberduck-ai/uberduck-ml-dev#164]
I recently came back to the Uberduck.ai website and its text-to-speech page, and the character voice clone feature of the site is all gone. Why is that?

**Comment by sjkoelle** [comment]
Legal uncertainty

**Comment by ToxicHolyGrenade** [comment]
So... it's not going to be put back? Or should it go through the courts first?

**Comment by ToxicHolyGrenade** [comment]
@sjkoelle So... it's not going to be put back? Or should it go through the courts first?
