### ISSUE TITLE
Regarding Character Voice Cloning 2: Test in Courts, and Make Compromises If Possible

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [uberduck-ai/uberduck-ml-dev#166]
I know it might be meaningless to make an offshoot to the last conversation related to the character voice cloning feature, but I am pleading you, on the behalf of the character voice cloning community, to test this all in court, and to make compromises if this all can be feasible.

Because character voice cloning is very useful when creating fan based content, especially when it comes to Gmod animations. And besides, there are people like myself, who wants to use it for fun and that's about it.

What I would propose, is to create some sort of online virtual license if people are to use the programs, and to also increase accountability of those who use the program as well. The important obligations however, is that the personal information will NOT be shared to the authorities unless the person is abusing the program. The virtual license should also not be susceptible to expiration, and it must be free to obtain due to the program not being a real-life sort of thing.

And what I would also want to see in turn, is to have rule of rule within the community, where everybody is equal under the rules. Particularly the people running the program.

**Comment by sjkoelle** [comment]
We appreciate the support. Unfortunately, sticking our heads out on this didn't make sense, but we are sure someone else will.

**Comment by ToxicHolyGrenade** [comment]
@sjkoelle What do you mean?
