### ISSUE TITLE
Pretrained models issue

### ISSUE THREAD

**Issue by johnpaulbin** [uberduck-ai/uberduck-ml-dev#22]
Training a Mellotron model is pretty difficult if you don't have 10,000 wav files in your dataset... Are any current models being trained to be used for warm starting / transfer learning?

The pretrained models in [Nvidia's official Mellotron implantation](https://github.com/NVIDIA/mellotron) are adequate, but not successful in my tests. [LJS (LJspeech) model](https://drive.google.com/open?id=1UwDARlUl8JvB2xSuyMFHFsIWELVpgQD4) is the only model I've gotten the best quality on, but the training times are still in the hours (5+ hours for 600 wavs to sound decently good) whilst on the other hand, regular Tacotron2 models take about 1 / 2 hours for the same amount of wavs.

Any info on any training / available models? If so, what is the dataset and ETA (if possible?)

**Comment by sjkoelle** [comment]
https://storage.cloud.google.com/uberduck-models/mellotron_360.pt?authuser=1 We are still having some issues with getting the multispeaker to sound less Scottish, but perhaps this is helpful.  Will let you know when we get a better one.

**Comment by sjkoelle** [comment]
This this one? https://drive.google.com/file/d/1N6mnk2BU5DlyXry3yPFcPr1z3p3kWC4u/view?usp=sharing

**Comment by johnpaulbin** [comment]
Interesting, what Hparams did you train it on?

I'm attempting to train only one speaker:

```
size mismatch for decoder.linear_projection.linear_layer.weight: copying a param with shape torch.Size([560, 1920]) from checkpoint, the shape in current model is torch.Size([80, 1920]).
	size mismatch for decoder.linear_projection.linear_layer.bias: copying a param with shape torch.Size([560]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for speaker_embedding.weight: copying a param with shape torch.Size([109, 128]) from checkpoint, the shape in current model is torch.Size([1, 128]).
```

**Comment by sjkoelle** [comment]
{
    "batch_size": 24,
    "checkpoint_name": null,
    "checkpoint_path": "checkpoints",
    "cudnn_enabled": true,
    "dataset_path": "../dataset",
    "debug": false ,
    "distributed_run": true,
    "epochs": 101,
    "epochs_per_checkpoint": 20,
    "filter_length": 1024,
    "fp16_run": false,
    "grad_clip_thresh": 1.0,
    "hop_length": 256,
    "include_f0": false,
    "learning_rate": 1e-3,
    "mask_padding": true,
    "max_wav_value": 32768.0,
    "mel_fmax": 8000,
    "mel_fmin": 0,
    "n_mel_channels": 80,
    "n_speakers": 108,
    "p_arpabet": 1.0,
    "sample_rate": 22050,
    "steps_per_sample": 100,
    "text_cleaners": ["english_cleaners"],
    "training_audiopaths_and_text": "train.txt",
    "val_audiopaths_and_text": "val.txt",
    "weight_decay": 1e-6,
    "win_length": 1024
}

I think you need to set n_speakers to 1?

**Comment by johnpaulbin** [comment]
would this require a older repo version to train? some required parameters are missing.

**Comment by sjkoelle** [comment]
hmmm will take a look

**Comment by zachwe** [comment]
@johnpaulbin Can you try this one?

```
{
    "batch_size": 100,
    "checkpoint_name": null,
    "checkpoint_path": "checkpoints2",
    "cudnn_enabled": true,
    "dataset_path": "./dataset",
    "debug": false,
    "distributed_run": false,
    "epochs": 501,
    "epochs_per_checkpoint": 20,
    "filter_length": 1024,
    "fp16_run": false,
    "grad_clip_thresh": 1.0,
    "hop_length": 256,
    "ignore_layers": null,
    "include_f0": false,
    "learning_rate": 1e-3,
    "log_dir": "runs/fp16-reductionwindow-5",
    "mask_padding": true,
    "max_wav_value": 32768.0,
    "mel_fmax": 8000,
    "mel_fmin": 0,
    "n_frames_per_step_initial": 7,
    "n_mel_channels": 80,
    "n_speakers": 109,
    "p_arpabet": 1.0,
    "reduction_window_schedule": [
        {
            "until_step": 10000,
            "batch_size": 100,
            "n_frames_per_step": 7
        },
        {
            "until_step": 50000,
            "batch_size": 100,
            "n_frames_per_step": 5
        },
        {
            "until_step": 60000,
            "batch_size": 100,
            "n_frames_per_step": 3
        },
        {
            "until_step": 70000,
            "batch_size": 80,
            "n_frames_per_step": 2
        },
        {
            "until_step": null,
            "batch_size": 80,
            "n_frames_per_step": 1
        }
    ],
    "sample_inference_speaker_ids": [
	    0, 1, 108
    ],
    "sample_rate": 22050,
    "steps_per_sample": 100,
    "text_cleaners": ["english_cleaners"],
    "training_audiopaths_and_text": "train.txt",
    "val_audiopaths_and_text": "val.txt",
    "weight_decay": 1e-6,
    "warm_start_name": "checkpoints2/mellotron_260.pt",
    "win_length": 1024
}
```

**Comment by johnpaulbin** [comment]
`RuntimeError: output with shape [1, 128] doesn't match the broadcast shape [109, 128]`
with:

```
{
    "batch_size": 24,
    "checkpoint_name": null,
    "checkpoint_path": "/content/checkpoints",
    "cudnn_enabled": true,
    "dataset_path": "./Narrarator",
    "debug": false,
    "distributed_run": false,
    "epochs": 501,
    "epochs_per_checkpoint": 20,
    "filter_length": 1024,
    "fp16_run": false,
    "grad_clip_thresh": 1.0,
    "hop_length": 256,
    "ignore_layers": ["speaker_embedding.weight"],
    "include_f0": false,
    "learning_rate": 1e-3,
    "log_dir": "runs/",
    "mask_padding": true,
    "max_wav_value": 32768.0,
    "mel_fmax": 8000,
    "mel_fmin": 0,
    "n_frames_per_step_initial": 7,
    "n_mel_channels": 80,
    "n_speakers": 1,
    "p_arpabet": 1.0,
    "reduction_window_schedule": [
        {
            "until_step": 10000,
            "batch_size": 100,
            "n_frames_per_step": 7
        },
        {
            "until_step": 50000,
            "batch_size": 100,
            "n_frames_per_step": 5
        },
        {
            "until_step": 60000,
            "batch_size": 100,
            "n_frames_per_step": 3
        },
        {
            "until_step": 70000,
            "batch_size": 80,
            "n_frames_per_step": 2
        },
        {
            "until_step": null,
            "batch_size": 80,
            "n_frames_per_step": 1
        }
    ],
    "sample_inference_speaker_ids": [
	    0
    ],
    "sample_rate": 22050,
    "steps_per_sample": 50,
    "text_cleaners": ["english_cleaners"],
    "training_audiopaths_and_text": "/content/uberduck-ml-dev/Narrarator/listARPA.txt",
    "val_audiopaths_and_text": "/content/uberduck-ml-dev/Narrarator/listARPA.txt",
    "weight_decay": 1e-6,
    "warm_start_name": "/content/uberduck-ml-dev/mellotron_360.pt",
    "win_length": 1024,
    "seed": 123
}
```

**Comment by johnpaulbin** [comment]
training seems to work if changing n_speakers to 109, but speakers are not in dataset, which may cause problems.

**Comment by johnpaulbin** [comment]
training finished successfully, but my solution might be only a temporary fix.
I noticed that synthesis is much more robust and emotional, thanks for your amazing effort-- can't wait for future models!
