### ISSUE TITLE
Disabling Validation Inference

### ISSUE THREAD

**Issue by gamerscruffy** [uberduck-ai/uberduck-ml-dev#72]
There should be a way to disable the validation parts between each epoch in the colab. For massive datasets, it can take up to 20 minutes to generate those samples. Being able to disable it would save a lot of time.

**Comment by sjkoelle** [comment]
Hey, sorry for the delay.  Thanks for bringing this up, will look into it.

**Comment by sjkoelle** [comment]
Just merged a fix!
