### ISSUE TITLE
Tacotron multispeaker training orders speakers unreliably

### ISSUE THREAD

**Issue by Sobsz** [uberduck-ai/uberduck-ml-dev#81]
No idea what could be causing it, but it seems to rely on speaker count: an 8-speaker model of mine had the inference IDs match the training ones, whereas a 20-speaker one is jumbled up. `dhama the llama` on Discord has been able to (eventually) find all the training voices in their 61-speaker model, so it's likely that the IDs are only being shuffled and not discarded.

**Comment by johnpaulbin** [comment]
bump

**Comment by sjkoelle** [comment]
Will take a look.

**Comment by johnpaulbin** [comment]
New information that might conclude that IDs are being treated as strings inside the trainer:

Here is a list LeifEricson put together inside discord:

![image](https://user-images.githubusercontent.com/43943237/164949940-3b19fcdd-a07d-48c8-9577-73296659ebef.png)

This is obviously incorrect sorting. This sorting is also consistent when sorting strings:

![image](https://user-images.githubusercontent.com/43943237/164949951-0ac3b725-999b-4570-b4b9-8d061f83998a.png)

e.g "10" is where "2" should be, etc.

**Comment by sjkoelle** [comment]
good catch.  just merged a fix that i think should work.
