### ISSUE TITLE
website - text to speech does not work - neighter on Chrome nor Safari (Mac)

### ISSUE THREAD

**Issue by klauskobald** [uberduck-ai/uberduck-ml-dev#82]
get a lot of errors in console:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/278428/163705598-aab53990-19c1-45fe-b09a-3c6e58fb1389.png">

**Comment by sjkoelle** [comment]
We've had some issues with our queueing system this week.  Not sure exactly what the cause is but we are adding more logging to find out!  Appreciate your patience.
